//
// Cartao.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Cartao: JSONEncodable {

    public enum Status: String { 
        case Ativo = "ATIVO"
        case Cancelado = "CANCELADO"
        case Bloqueado = "BLOQUEADO"
    }
    
    public var cvv: String?
    public var id: Int?
    public var nome: String?
    public var numero: String?
    public var senha: String?
    public var status: Status?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["cvv"] = self.cvv
        nillableDictionary["id"] = self.id
        nillableDictionary["nome"] = self.nome
        nillableDictionary["numero"] = self.numero
        nillableDictionary["senha"] = self.senha
        nillableDictionary["status"] = self.status?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
