//
// Transacao.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Transacao: JSONEncodable {

    public var dataTransacao: NSDate?
    public var id: Int?
    public var msg: String?
    public var valor: Double?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["dataTransacao"] = self.dataTransacao?.encodeToJSON()
        nillableDictionary["id"] = self.id
        nillableDictionary["msg"] = self.msg
        nillableDictionary["valor"] = self.valor
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
