<?php
/**
 * ContaApi
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.sdc.api.v1.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace br.com.conductor.sdc.api.v1;

use \br.com.conductor.sdc.api.v1.invoker\Configuration;
use \br.com.conductor.sdc.api.v1.invoker\ApiClient;
use \br.com.conductor.sdc.api.v1.invoker\ApiException;
use \br.com.conductor.sdc.api.v1.invoker\ObjectSerializer;

/**
 * ContaApi Class Doc Comment
 *
 * @category Class
 * @package  br.com.conductor.sdc.api.v1.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContaApi
{

    /**
     * API Client
     * @var \br.com.conductor.sdc.api.v1.invoker\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \br.com.conductor.sdc.api.v1.invoker\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://localhost/');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \br.com.conductor.sdc.api.v1.invoker\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \br.com.conductor.sdc.api.v1.invoker\ApiClient $apiClient set the API client
     * @return ContaApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * createUsingPOST1
     *
     * Cria uma conta
     *
     * @param \br.com.conductor.sdc.api.v1.model\Conta $conta conta (required)
     * @return \br.com.conductor.sdc.api.v1.model\Conta
     * @throws \br.com.conductor.sdc.api.v1.invoker\ApiException on non-2xx response
     */
    public function createUsingPOST1($conta)
    {
        list($response, $statusCode, $httpHeader) = $this->createUsingPOST1WithHttpInfo ($conta);
        return $response; 
    }


    /**
     * createUsingPOST1WithHttpInfo
     *
     * Cria uma conta
     *
     * @param \br.com.conductor.sdc.api.v1.model\Conta $conta conta (required)
     * @return Array of \br.com.conductor.sdc.api.v1.model\Conta, HTTP status code, HTTP response headers (array of strings)
     * @throws \br.com.conductor.sdc.api.v1.invoker\ApiException on non-2xx response
     */
    public function createUsingPOST1WithHttpInfo($conta)
    {
        
        // verify the required parameter 'conta' is set
        if ($conta === null) {
            throw new \InvalidArgumentException('Missing the required parameter $conta when calling createUsingPOST1');
        }
  
        // parse inputs
        $resourcePath = "/v1/contas";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($conta)) {
            $_tempBody = $conta;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('access_token');
        if (strlen($apiKey) !== 0) {
            $headerParams['access_token'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\br.com.conductor.sdc.api.v1.model\Conta'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::deserialize($response, '\br.com.conductor.sdc.api.v1.model\Conta', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::deserialize($e->getResponseBody(), '\br.com.conductor.sdc.api.v1.model\Conta', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteUsingDELETE
     *
     * Deleta uma conta
     *
     * @param int $id id (required)
     * @return \br.com.conductor.sdc.api.v1.model\ResponseEntity
     * @throws \br.com.conductor.sdc.api.v1.invoker\ApiException on non-2xx response
     */
    public function deleteUsingDELETE($id)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteUsingDELETEWithHttpInfo ($id);
        return $response; 
    }


    /**
     * deleteUsingDELETEWithHttpInfo
     *
     * Deleta uma conta
     *
     * @param int $id id (required)
     * @return Array of \br.com.conductor.sdc.api.v1.model\ResponseEntity, HTTP status code, HTTP response headers (array of strings)
     * @throws \br.com.conductor.sdc.api.v1.invoker\ApiException on non-2xx response
     */
    public function deleteUsingDELETEWithHttpInfo($id)
    {
        
        // verify the required parameter 'id' is set
        if ($id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling deleteUsingDELETE');
        }
  
        // parse inputs
        $resourcePath = "/v1/contas/{id}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($id !== null) {
            $resourcePath = str_replace(
                "{" . "id" . "}",
                $this->apiClient->getSerializer()->toPathValue($id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('access_token');
        if (strlen($apiKey) !== 0) {
            $headerParams['access_token'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams, '\br.com.conductor.sdc.api.v1.model\ResponseEntity'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::deserialize($response, '\br.com.conductor.sdc.api.v1.model\ResponseEntity', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::deserialize($e->getResponseBody(), '\br.com.conductor.sdc.api.v1.model\ResponseEntity', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getAllUsingGET1
     *
     * Retorna todas as contas
     *
     * @return \br.com.conductor.sdc.api.v1.model\Conta[]
     * @throws \br.com.conductor.sdc.api.v1.invoker\ApiException on non-2xx response
     */
    public function getAllUsingGET1()
    {
        list($response, $statusCode, $httpHeader) = $this->getAllUsingGET1WithHttpInfo ();
        return $response; 
    }


    /**
     * getAllUsingGET1WithHttpInfo
     *
     * Retorna todas as contas
     *
     * @return Array of \br.com.conductor.sdc.api.v1.model\Conta[], HTTP status code, HTTP response headers (array of strings)
     * @throws \br.com.conductor.sdc.api.v1.invoker\ApiException on non-2xx response
     */
    public function getAllUsingGET1WithHttpInfo()
    {
        
  
        // parse inputs
        $resourcePath = "/v1/contas";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('access_token');
        if (strlen($apiKey) !== 0) {
            $headerParams['access_token'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\br.com.conductor.sdc.api.v1.model\Conta[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::deserialize($response, '\br.com.conductor.sdc.api.v1.model\Conta[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::deserialize($e->getResponseBody(), '\br.com.conductor.sdc.api.v1.model\Conta[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getOneUsingGET1
     *
     * Retorna uma conta
     *
     * @param int $id id (required)
     * @return \br.com.conductor.sdc.api.v1.model\Conta
     * @throws \br.com.conductor.sdc.api.v1.invoker\ApiException on non-2xx response
     */
    public function getOneUsingGET1($id)
    {
        list($response, $statusCode, $httpHeader) = $this->getOneUsingGET1WithHttpInfo ($id);
        return $response; 
    }


    /**
     * getOneUsingGET1WithHttpInfo
     *
     * Retorna uma conta
     *
     * @param int $id id (required)
     * @return Array of \br.com.conductor.sdc.api.v1.model\Conta, HTTP status code, HTTP response headers (array of strings)
     * @throws \br.com.conductor.sdc.api.v1.invoker\ApiException on non-2xx response
     */
    public function getOneUsingGET1WithHttpInfo($id)
    {
        
        // verify the required parameter 'id' is set
        if ($id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling getOneUsingGET1');
        }
  
        // parse inputs
        $resourcePath = "/v1/contas/{id}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($id !== null) {
            $resourcePath = str_replace(
                "{" . "id" . "}",
                $this->apiClient->getSerializer()->toPathValue($id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('access_token');
        if (strlen($apiKey) !== 0) {
            $headerParams['access_token'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\br.com.conductor.sdc.api.v1.model\Conta'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::deserialize($response, '\br.com.conductor.sdc.api.v1.model\Conta', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::deserialize($e->getResponseBody(), '\br.com.conductor.sdc.api.v1.model\Conta', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * updateUsingPUT1
     *
     * Atualiza uma conta
     *
     * @param \br.com.conductor.sdc.api.v1.model\Conta $conta conta (required)
     * @return \br.com.conductor.sdc.api.v1.model\Conta
     * @throws \br.com.conductor.sdc.api.v1.invoker\ApiException on non-2xx response
     */
    public function updateUsingPUT1($conta)
    {
        list($response, $statusCode, $httpHeader) = $this->updateUsingPUT1WithHttpInfo ($conta);
        return $response; 
    }


    /**
     * updateUsingPUT1WithHttpInfo
     *
     * Atualiza uma conta
     *
     * @param \br.com.conductor.sdc.api.v1.model\Conta $conta conta (required)
     * @return Array of \br.com.conductor.sdc.api.v1.model\Conta, HTTP status code, HTTP response headers (array of strings)
     * @throws \br.com.conductor.sdc.api.v1.invoker\ApiException on non-2xx response
     */
    public function updateUsingPUT1WithHttpInfo($conta)
    {
        
        // verify the required parameter 'conta' is set
        if ($conta === null) {
            throw new \InvalidArgumentException('Missing the required parameter $conta when calling updateUsingPUT1');
        }
  
        // parse inputs
        $resourcePath = "/v1/contas";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($conta)) {
            $_tempBody = $conta;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('access_token');
        if (strlen($apiKey) !== 0) {
            $headerParams['access_token'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams, '\br.com.conductor.sdc.api.v1.model\Conta'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::deserialize($response, '\br.com.conductor.sdc.api.v1.model\Conta', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::deserialize($e->getResponseBody(), '\br.com.conductor.sdc.api.v1.model\Conta', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
