using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Conductor.SDC.Api;
using Conductor.SDC.Model;
using Conductor.SDC.Client;
using System.Reflection;

namespace Conductor.SDC.Test
{
    /// <summary>
    ///  Class for testing Cartao
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartaoTests
    {
        private Cartao instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Cartao();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Cartao
        /// </summary>
        [Test]
        public void CartaoInstanceTest()
        {
            Assert.IsInstanceOf<Cartao> (instance, "instance is a Cartao");
        }

        
        /// <summary>
        /// Test the property 'Cvv' 
        /// </summary>
        [Test]
        public void CvvTest()
        {
            // TODO: unit test for the property 'Cvv' 
        }
        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Nome' 
        /// </summary>
        [Test]
        public void NomeTest()
        {
            // TODO: unit test for the property 'Nome' 
        }
        
        /// <summary>
        /// Test the property 'Numero' 
        /// </summary>
        [Test]
        public void NumeroTest()
        {
            // TODO: unit test for the property 'Numero' 
        }
        
        /// <summary>
        /// Test the property 'Senha' 
        /// </summary>
        [Test]
        public void SenhaTest()
        {
            // TODO: unit test for the property 'Senha' 
        }
        
        /// <summary>
        /// Test the property 'Status' 
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO: unit test for the property 'Status' 
        }
        

    }

}
