using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Conductor.SDC.Api;
using Conductor.SDC.Model;
using Conductor.SDC.Client;
using System.Reflection;

namespace Conductor.SDC.Test
{
    /// <summary>
    ///  Class for testing Conta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContaTests
    {
        private Conta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Conta();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Conta
        /// </summary>
        [Test]
        public void ContaInstanceTest()
        {
            Assert.IsInstanceOf<Conta> (instance, "instance is a Conta");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Nome' 
        /// </summary>
        [Test]
        public void NomeTest()
        {
            // TODO: unit test for the property 'Nome' 
        }
        

    }

}
