using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Conductor.SDC.Api;
using Conductor.SDC.Model;
using Conductor.SDC.Client;
using System.Reflection;

namespace Conductor.SDC.Test
{
    /// <summary>
    ///  Class for testing Limite
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LimiteTests
    {
        private Limite instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Limite();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Limite
        /// </summary>
        [Test]
        public void LimiteInstanceTest()
        {
            Assert.IsInstanceOf<Limite> (instance, "instance is a Limite");
        }

        
        /// <summary>
        /// Test the property 'Valor' 
        /// </summary>
        [Test]
        public void ValorTest()
        {
            // TODO: unit test for the property 'Valor' 
        }
        

    }

}
