using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Conductor.SDC.Api;
using Conductor.SDC.Model;
using Conductor.SDC.Client;
using System.Reflection;

namespace Conductor.SDC.Test
{
    /// <summary>
    ///  Class for testing ResponseEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseEntityTests
    {
        private ResponseEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ResponseEntity();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of ResponseEntity
        /// </summary>
        [Test]
        public void ResponseEntityInstanceTest()
        {
            Assert.IsInstanceOf<ResponseEntity> (instance, "instance is a ResponseEntity");
        }

        
        /// <summary>
        /// Test the property 'Body' 
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO: unit test for the property 'Body' 
        }
        
        /// <summary>
        /// Test the property 'StatusCode' 
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO: unit test for the property 'StatusCode' 
        }
        

    }

}
