#import <Foundation/Foundation.h>
#import "SDCResponseEntity.h"
#import "SDCCartao.h"
#import "SDCObject.h"
#import "SDCApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SDCCartaoApi: NSObject

@property(nonatomic, assign)SDCApiClient *apiClient;

-(instancetype) initWithApiClient:(SDCApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SDCCartaoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SDCCartaoApi*) sharedAPI;
///
///
/// Bloquear um cart\u00EF\u00BF\u00BDo.
/// Bloquear um cart\u00EF\u00BF\u00BDo.
///
/// @param idConta ID da Conta
/// @param idCartao Cart\u00EF\u00BF\u00BDo a ser bloqueado
/// 
///
/// @return SDCResponseEntity*
-(NSNumber*) bloquearUsingPUTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCResponseEntity* output, NSError* error)) handler;


///
///
/// Cancelar um cart\u00EF\u00BF\u00BDo
/// Cancelar um cart\u00EF\u00BF\u00BDo
///
/// @param idConta ID da Conta
/// @param idCartao Cart\u00EF\u00BF\u00BDo a ser cancelado
/// 
///
/// @return SDCResponseEntity*
-(NSNumber*) cancelarUsingDELETEWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCResponseEntity* output, NSError* error)) handler;


///
///
/// Cria um cart\u00EF\u00BF\u00BDo
/// Cria um cart\u00EF\u00BF\u00BDo
///
/// @param idConta ID da Conta
/// @param cartao Cart\u00EF\u00BF\u00BDo a ser criado
/// 
///
/// @return SDCCartao*
-(NSNumber*) createUsingPOSTWithIdConta: (NSNumber*) idConta
    cartao: (SDCCartao*) cartao
    completionHandler: (void (^)(SDCCartao* output, NSError* error)) handler;


///
///
/// Creditar dinheiro em um cart\u00EF\u00BF\u00BDo
/// Creditar dinheiro em um cart\u00EF\u00BF\u00BDo
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cartao a ser creditado
/// @param valor Valor a ser creditado
/// 
///
/// @return SDCResponseEntity*
-(NSNumber*) creditarUsingPUTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    valor: (NSNumber*) valor
    completionHandler: (void (^)(SDCResponseEntity* output, NSError* error)) handler;


///
///
/// Desbloquear um cart\u00EF\u00BF\u00BDo.
/// Desbloquear um cart\u00EF\u00BF\u00BDo.
///
/// @param idConta ID da Conta
/// @param idCartao Cart\u00EF\u00BF\u00BDo a ser desbloqueado
/// 
///
/// @return SDCResponseEntity*
-(NSNumber*) desbloquearUsingPUTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCResponseEntity* output, NSError* error)) handler;


///
///
/// Retonar os extratos de transa\u00EF\u00BF\u00BD\u00EF\u00BF\u00BDes do cart\u00EF\u00BF\u00BDo
/// Retorna os extratos de todas as transa\u00EF\u00BF\u00BD\u00EF\u00BF\u00BDes de um determinado cart\u00EF\u00BF\u00BDo
///
/// @param idConta ID da Conta
/// @param idCartao ID do cart\u00EF\u00BF\u00BDo
/// 
///
/// @return SDCResponseEntity*
-(NSNumber*) extratosUsingPOSTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCResponseEntity* output, NSError* error)) handler;


///
///
/// Retona todos os cart\u00EF\u00BF\u00BDo de uma conta
/// Retona todos os cart\u00EF\u00BF\u00BDo de uma conta
///
/// @param idConta ID da Conta
/// 
///
/// @return NSArray<SDCCartao>*
-(NSNumber*) getAllUsingGETWithIdConta: (NSNumber*) idConta
    completionHandler: (void (^)(NSArray<SDCCartao>* output, NSError* error)) handler;


///
///
/// Retorna um cart\u00EF\u00BF\u00BDo
/// Retorna um cart\u00EF\u00BF\u00BDo
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cart\u00EF\u00BF\u00BDo
/// 
///
/// @return SDCCartao*
-(NSNumber*) getOneUsingGETWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCCartao* output, NSError* error)) handler;


///
///
/// Consultar o limite de um determinado cart\u00EF\u00BF\u00BDo
/// Consultar o limite de um determinado cart\u00EF\u00BF\u00BDo
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cartao a ser creditado
/// 
///
/// @return SDCResponseEntity*
-(NSNumber*) limiteUsingGETWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCResponseEntity* output, NSError* error)) handler;


///
///
/// Transacionar valores
/// Transacionar algum valor utilizando um determinado cart\u00EF\u00BF\u00BDo
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cartao a ser creditado
/// @param valor Valor da transa\u00EF\u00BF\u00BD\u00EF\u00BF\u00BDo
/// 
///
/// @return SDCResponseEntity*
-(NSNumber*) transacionarUsingPUTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    valor: (NSNumber*) valor
    completionHandler: (void (^)(SDCResponseEntity* output, NSError* error)) handler;


///
///
/// Transferir valores entre dois cart\u00EF\u00BF\u00BDes distintos
/// Transferir valores entre dois cart\u00EF\u00BF\u00BDes
///
/// @param idConta ID da Conta do cart\u00EF\u00BF\u00BDo de origem
/// @param idCartao ID do cart\u00EF\u00BF\u00BDo de origem
/// @param idCartaoDestino ID do cart\u00EF\u00BF\u00BDo de destino
/// @param valor Valor a ser transferido
/// 
///
/// @return SDCResponseEntity*
-(NSNumber*) transferirUsingPOSTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    idCartaoDestino: (NSNumber*) idCartaoDestino
    valor: (NSNumber*) valor
    completionHandler: (void (^)(SDCResponseEntity* output, NSError* error)) handler;


///
///
/// Atualiza um cart\u00EF\u00BF\u00BDo
/// Atualiza um cart\u00EF\u00BF\u00BDo
///
/// @param idConta ID da Conta
/// @param cartao Cart\u00EF\u00BF\u00BDo a ser atualizado
/// 
///
/// @return SDCCartao*
-(NSNumber*) updateUsingPUTWithIdConta: (NSNumber*) idConta
    cartao: (SDCCartao*) cartao
    completionHandler: (void (^)(SDCCartao* output, NSError* error)) handler;



@end
