#import <Foundation/Foundation.h>
#import "SDCResponse.h"
#import "SDCCartao.h"
#import "SDCTransacao.h"
#import "SDCLimite.h"
#import "SDCObject.h"
#import "SDCApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SDCCartaoApi: NSObject

@property(nonatomic, assign)SDCApiClient *apiClient;

-(instancetype) initWithApiClient:(SDCApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SDCCartaoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SDCCartaoApi*) sharedAPI;
///
///
/// Bloquear um cart\u00C3\u00A3o.
/// Bloquear um cart\u00C3\u00A3o.
///
/// @param idConta ID da Conta
/// @param idCartao Cart\u00C3\u00A3o a ser bloqueado
/// 
///
/// @return SDCResponse*
-(NSNumber*) bloquearUsingPUTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCResponse* output, NSError* error)) handler;


///
///
/// Cancelar um cart\u00C3\u00A3o
/// Cancelar um determinado cart\u00C3\u00A3o
///
/// @param idConta ID da Conta
/// @param idCartao Cart\u00C3\u00A3o a ser cancelado
/// 
///
/// @return SDCResponse*
-(NSNumber*) cancelarUsingDELETEWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCResponse* output, NSError* error)) handler;


///
///
/// Cria um cart\u00C3\u00A3o
/// Voc\u00C3\u00AA pode criar um cart\u00C3\u00A3o ligado h\u00C3\u00A1 uma determinada conta.
///
/// @param idConta ID da Conta
/// @param cartao Cart\u00C3\u00A3o a ser criado
/// 
///
/// @return SDCCartao*
-(NSNumber*) createUsingPOSTWithIdConta: (NSNumber*) idConta
    cartao: (SDCCartao*) cartao
    completionHandler: (void (^)(SDCCartao* output, NSError* error)) handler;


///
///
/// Creditar dinheiro em um cart\u00C3\u00A3o
/// Com esse m\u00C3\u00A9todo \u00C3\u00A9 possivel creditar qualquer valor em um cart\u00C3\u00A3o.
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cartao a ser creditado
/// @param valor Valor a ser creditado
/// 
///
/// @return SDCResponse*
-(NSNumber*) creditarUsingPUTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    valor: (NSNumber*) valor
    completionHandler: (void (^)(SDCResponse* output, NSError* error)) handler;


///
///
/// Desbloquear um cart\u00C3\u00A3o.
/// Desbloquear um determinado cart\u00C3\u00A3o.
///
/// @param idConta ID da Conta
/// @param idCartao Cart\u00C3\u00A3o a ser desbloqueado
/// 
///
/// @return SDCResponse*
-(NSNumber*) desbloquearUsingPUTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCResponse* output, NSError* error)) handler;


///
///
/// Retonar os extratos de transa\u00C3\u00A7oes do cart\u00C3\u00A3o
/// Retorna os extratos de todas as transa\u00C3\u00A7oes de um determinado cart\u00C3\u00A3o
///
/// @param idConta ID da Conta
/// @param idCartao ID do cart\u00C3\u00A3o
/// 
///
/// @return NSArray<SDCTransacao>*
-(NSNumber*) extratosUsingPOSTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(NSArray<SDCTransacao>* output, NSError* error)) handler;


///
///
/// Retona todos os cart\u00C3\u00A3o de uma conta
/// Consulte todos os carteos de uma determinada conta.
///
/// @param idConta ID da Conta
/// 
///
/// @return NSArray<SDCCartao>*
-(NSNumber*) getAllUsingGETWithIdConta: (NSNumber*) idConta
    completionHandler: (void (^)(NSArray<SDCCartao>* output, NSError* error)) handler;


///
///
/// Retorna um cart\u00C3\u00A3o
/// Consulte um determinado cart\u00C3\u00A3o
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cart\u00C3\u00A3o
/// 
///
/// @return SDCCartao*
-(NSNumber*) getOneUsingGETWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCCartao* output, NSError* error)) handler;


///
///
/// Retorna o limite do cart\u00C3\u00A3o
/// Consultar o limite de um determinado cart\u00C3\u00A3o
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cartao a ser creditado
/// 
///
/// @return SDCLimite*
-(NSNumber*) limiteUsingGETWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    completionHandler: (void (^)(SDCLimite* output, NSError* error)) handler;


///
///
/// Transacionar valores
/// Transacionar algum valor utilizando um determinado cart\u00C3\u00A3o
///
/// @param idConta ID da Conta
/// @param idCartao ID do Cartao a ser creditado
/// @param valor Valor da transa\u00C3\u00A7\u00C3\u00A3o
/// 
///
/// @return SDCResponse*
-(NSNumber*) transacionarUsingPUTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    valor: (NSNumber*) valor
    completionHandler: (void (^)(SDCResponse* output, NSError* error)) handler;


///
///
/// Transferir valores entre dois cart\u00C3\u00B5es distintos
/// Com esse m\u00C3\u00A9todo \u00C3\u00A9 permitido transferir qualquer valores entre dois cart\u00C3\u00B5es. Basta o cart\u00C3\u00A3o possuir limite e estar desbloqueado.
///
/// @param idConta ID da Conta do cart\u00C3\u00A3o de origem
/// @param idCartao ID do cart\u00C3\u00A3o de origem
/// @param idCartaoDestino ID do cart\u00C3\u00A3o de destino
/// @param valor Valor a ser transferido
/// 
///
/// @return SDCResponse*
-(NSNumber*) transferirUsingPOSTWithIdConta: (NSNumber*) idConta
    idCartao: (NSNumber*) idCartao
    idCartaoDestino: (NSNumber*) idCartaoDestino
    valor: (NSNumber*) valor
    completionHandler: (void (^)(SDCResponse* output, NSError* error)) handler;


///
///
/// Atualiza um cart\u00C3\u00A3o
/// Atualiza um determinado cart\u00C3\u00A3o
///
/// @param idConta ID da Conta
/// @param cartao Cart\u00C3\u00A3o a ser atualizado
/// 
///
/// @return SDCCartao*
-(NSNumber*) updateUsingPUTWithIdConta: (NSNumber*) idConta
    cartao: (SDCCartao*) cartao
    completionHandler: (void (^)(SDCCartao* output, NSError* error)) handler;



@end
