#import <Foundation/Foundation.h>
#import "SDCObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SDCConta
@end

@interface SDCConta : SDCObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* nome;

@end
