#import <Foundation/Foundation.h>
#import "SDCConta.h"
#import "SDCResponse.h"
#import "SDCObject.h"
#import "SDCApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SDCContaApi: NSObject

@property(nonatomic, assign)SDCApiClient *apiClient;

-(instancetype) initWithApiClient:(SDCApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SDCContaApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SDCContaApi*) sharedAPI;
///
///
/// Cria uma conta
/// Cria uma conta
///
/// @param conta conta
/// 
///
/// @return SDCConta*
-(NSNumber*) createUsingPOST1WithConta: (SDCConta*) conta
    completionHandler: (void (^)(SDCConta* output, NSError* error)) handler;


///
///
/// Deleta uma conta
/// Deleta uma conta
///
/// @param _id id
/// 
///
/// @return SDCResponse*
-(NSNumber*) deleteUsingDELETEWithId: (NSNumber*) _id
    completionHandler: (void (^)(SDCResponse* output, NSError* error)) handler;


///
///
/// Retorna todas as contas
/// Retorna todas as contas
///
/// 
///
/// @return NSArray<SDCConta>*
-(NSNumber*) getAllUsingGET1WithCompletionHandler: 
    (void (^)(NSArray<SDCConta>* output, NSError* error)) handler;


///
///
/// Retorna uma conta
/// Retorna uma conta
///
/// @param _id id
/// 
///
/// @return SDCConta*
-(NSNumber*) getOneUsingGET1WithId: (NSNumber*) _id
    completionHandler: (void (^)(SDCConta* output, NSError* error)) handler;


///
///
/// Atualiza uma conta
/// Atualiza uma conta
///
/// @param conta conta
/// 
///
/// @return SDCConta*
-(NSNumber*) updateUsingPUT1WithConta: (SDCConta*) conta
    completionHandler: (void (^)(SDCConta* output, NSError* error)) handler;



@end
