#import <Foundation/Foundation.h>
#import "SDCObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SDCCartao
@end

@interface SDCCartao : SDCObject


@property(nonatomic) NSString* cvv;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* nome;

@property(nonatomic) NSString* numero;

@property(nonatomic) NSString* senha;

@property(nonatomic) NSString* status;

@end
