#import <Foundation/Foundation.h>
#import "SDCObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SDCExtrato
@end

@interface SDCExtrato : SDCObject


@property(nonatomic) NSDate* data;

@property(nonatomic) NSString* tipo;

@property(nonatomic) NSNumber* valor;

@end
