#import <Foundation/Foundation.h>
#import "SDCObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SDCResponseEntity
@end

@interface SDCResponseEntity : SDCObject


@property(nonatomic) NSObject* body;

@property(nonatomic) NSString* statusCode;

@end
