#import <Foundation/Foundation.h>
#import "SDCObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SDCTransacao
@end

@interface SDCTransacao : SDCObject


@property(nonatomic) NSDate* dataTransacao;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* msg;

@property(nonatomic) NSNumber* valor;

@end
