<?php
/**
 * Transacao
 *
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.sdc.api.v1.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace br.com.conductor.sdc.api.v1.model;

use \ArrayAccess;
/**
 * Transacao Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     br.com.conductor.sdc.api.v1.invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Transacao implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'data_transacao' => '\DateTime',
        'id' => 'int',
        'msg' => 'string',
        'valor' => 'double'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'data_transacao' => 'dataTransacao',
        'id' => 'id',
        'msg' => 'msg',
        'valor' => 'valor'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'data_transacao' => 'setDataTransacao',
        'id' => 'setId',
        'msg' => 'setMsg',
        'valor' => 'setValor'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'data_transacao' => 'getDataTransacao',
        'id' => 'getId',
        'msg' => 'getMsg',
        'valor' => 'getValor'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $data_transacao 
      * @var \DateTime
      */
    protected $data_transacao;
    
    /**
      * $id 
      * @var int
      */
    protected $id;
    
    /**
      * $msg 
      * @var string
      */
    protected $msg;
    
    /**
      * $valor 
      * @var double
      */
    protected $valor;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->data_transacao = $data["data_transacao"];
            $this->id = $data["id"];
            $this->msg = $data["msg"];
            $this->valor = $data["valor"];
        }
    }
    
    /**
     * Gets data_transacao
     * @return \DateTime
     */
    public function getDataTransacao()
    {
        return $this->data_transacao;
    }
  
    /**
     * Sets data_transacao
     * @param \DateTime $data_transacao 
     * @return $this
     */
    public function setDataTransacao($data_transacao)
    {
        
        $this->data_transacao = $data_transacao;
        return $this;
    }
    
    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param int $id 
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets msg
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }
  
    /**
     * Sets msg
     * @param string $msg 
     * @return $this
     */
    public function setMsg($msg)
    {
        
        $this->msg = $msg;
        return $this;
    }
    
    /**
     * Gets valor
     * @return double
     */
    public function getValor()
    {
        return $this->valor;
    }
  
    /**
     * Sets valor
     * @param double $valor 
     * @return $this
     */
    public function setValor($valor)
    {
        
        $this->valor = $valor;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\br.com.conductor.sdc.api.v1.invoker\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
