=begin
PIER Labs

PIER Labs - Primeiro Hach Day SBC UFPB

OpenAPI spec version: 0.0.1
Contact: pierlabs@conductor.com.br
Generated by: https://github.com/swagger-api/swagger-codegen.git

License: Apache 2.0
http://www.apache.org/licenses/LICENSE-2.0.html

Terms of Service: http://pierlabs.io/terms/

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SDC::ResponseEntity
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ResponseEntity' do
  before do
    # run before each test
    @instance = SDC::ResponseEntity.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ResponseEntity' do
    it 'should create an instact of ResponseEntity' do
      @instance.should be_a(SDC::ResponseEntity) 
    end
  end
  describe 'test attribute "body"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "status_code"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

