<?php
/**
 * CartaoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.sdc.api.v1.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace br.com.conductor.sdc.api.v1;

use \br.com.conductor.sdc.api.v1.invoker\Configuration;
use \br.com.conductor.sdc.api.v1.invoker\ApiClient;
use \br.com.conductor.sdc.api.v1.invoker\ApiException;
use \br.com.conductor.sdc.api.v1.invoker\ObjectSerializer;

/**
 * CartaoApiTest Class Doc Comment
 *
 * @category Class
 * @package  br.com.conductor.sdc.api.v1.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CartaoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for bloquearUsingPUT
     *
     * Bloquear um cart\u00C3\u00A3o.
     *
     */
    public function test_bloquearUsingPUT() {

    }
    
    /**
     * Test case for cancelarUsingDELETE
     *
     * Cancelar um cart\u00C3\u00A3o
     *
     */
    public function test_cancelarUsingDELETE() {

    }
    
    /**
     * Test case for createUsingPOST
     *
     * Cria um cart\u00C3\u00A3o
     *
     */
    public function test_createUsingPOST() {

    }
    
    /**
     * Test case for creditarUsingPUT
     *
     * Creditar dinheiro em um cart\u00C3\u00A3o
     *
     */
    public function test_creditarUsingPUT() {

    }
    
    /**
     * Test case for desbloquearUsingPUT
     *
     * Desbloquear um cart\u00C3\u00A3o.
     *
     */
    public function test_desbloquearUsingPUT() {

    }
    
    /**
     * Test case for extratosUsingPOST
     *
     * Extratos de transa\u00C3\u00A7oes
     *
     */
    public function test_extratosUsingPOST() {

    }
    
    /**
     * Test case for getAllUsingGET
     *
     * Retona todos os cart\u00C3\u00A3o de uma conta
     *
     */
    public function test_getAllUsingGET() {

    }
    
    /**
     * Test case for getOneUsingGET
     *
     * Retorna um cart\u00C3\u00A3o
     *
     */
    public function test_getOneUsingGET() {

    }
    
    /**
     * Test case for limiteUsingGET
     *
     * Retorna o limite do cart\u00C3\u00A3o
     *
     */
    public function test_limiteUsingGET() {

    }
    
    /**
     * Test case for transacionarUsingPUT
     *
     * Transacionar valores
     *
     */
    public function test_transacionarUsingPUT() {

    }
    
    /**
     * Test case for transferirUsingPOST
     *
     * Transferir valores entre dois cart\u00C3\u00B5es distintos
     *
     */
    public function test_transferirUsingPOST() {

    }
    
    /**
     * Test case for updateUsingPUT
     *
     * Atualiza um cart\u00C3\u00A3o
     *
     */
    public function test_updateUsingPUT() {

    }
    
}
